/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Aug 28 18:29:28 CST 2007 by MyEclipse Hibernate Tool.
 */
package com.ksd.zzw.entity;

import java.io.Serializable;
import java.sql.Timestamp;

/**
 *
 */
public class Notice implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -2103667920118899273L;
	private int hashValue = 0;
    private Integer id;
    private String sender;
    private String title;
    private String content;
    private Timestamp sendtime;


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.sql.Timestamp getSendtime() {
        return sendtime;
    }

    public void setSendtime(java.sql.Timestamp sendtime) {
        this.sendtime = sendtime;
    }

    public Notice() {

    }

    public Notice(Integer id) {
        this.id = id;
    }

    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Notice))
            return false;
        Notice that = (Notice) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
