/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Aug 28 18:29:29 CST 2007 by MyEclipse Hibernate Tool.
 */
package com.ksd.zzw.entity;

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * A class that represents a row in the sms table.
 * You can customize the behavior of this class by editing the class, {@link Sms()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public class Sms implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -7821903196451225222L;
	private int hashValue = 0;
    private Integer id;
    private String username;
    private String sender;
    private String message;
    private Timestamp sendtime;
    private String isread;

    public Sms() {
    }

    public Sms(Integer id) {
        this.setId(id);
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Timestamp getSendtime() {
        return sendtime;
    }

    public void setSendtime(Timestamp sendtime) {
        this.sendtime = sendtime;
    }

    public String getIsread() {
        return isread;
    }

    public void setIsread(String isread) {
        this.isread = isread;
    }

    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Sms))
            return false;
        Sms that = (Sms) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

    @Override
    public String toString() {
        return "Sms{" +
                "hashValue=" + hashValue +
                ", id=" + id +
                ", username='" + username + '\'' +
                ", sender='" + sender + '\'' +
                ", message='" + message + '\'' +
                ", sendtime=" + sendtime +
                ", isread='" + isread + '\'' +
                '}';
    }
}
